<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.neweraoragnizations.webhook</groupId>
        <artifactId>webhook-platform</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>webhook-persistence</artifactId>
    <packaging>jar</packaging>
    <dependencies>
            <!-- JPA annotations (Entity, Table, Id, etc.) -->
            <dependency>
                <groupId>jakarta.persistence</groupId>
                <artifactId>jakarta.persistence-api</artifactId>
            </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-jpa</artifactId>
        </dependency>
    </dependencies>

</project>
