spring:
  application-context:
    name: CUSTOMER-SERVICE
  profiles:
    active: dev
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8083
  servlet:
    context-path: /customer-service


